server:
  port: 3344

spring:
  application:
    name: spring-cloud-config-server
  cloud:
    config:
      server:
        git:
          uri: git@github.com:wujack778/spring-cloud-config.git
          search-paths:
            - spring-cloud-config
      label: master

