server:
  port: 3344

spring:
  application:
    name: spring-cloud-config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/wujack778/spring-cloud-config.git
          search-paths:
            - spring-cloud-config
          username: wujack778
          password: Wgk123**
      #          clone-on-start: true
      label: master


#      /{application}/{profile}[/{label}]
        #/{application}-{profile}.yml
        #/{label}/{application}-{profile}.yml
      #/{application}-{profile}.properties
      #/{label}/{application}-{profile}.properties

